import type { SessionConfig } from '../session';
import { generatedTexts, stageDurations } from './surrender-texts';

export const erotic: SessionConfig = {
  id: 'surrender',
  name: 'Surrender',
  description: 'An erotic submission hypnosis session blending dominance framing with permissive Ericksonian technique.',
  icon: '\u{1F525}',
  theme: {
    textColor: '#ffb0c0',
    textGlow: 'rgba(255, 120, 160, 0.5)',
    primaryColor: [0.6, 0.08, 0.2],
    secondaryColor: [0.45, 0.04, 0.3],
    accentColor: [0.85, 0.2, 0.45],
    bgColor: [0.05, 0.01, 0.03],
    particleColor: [0.7, 0.15, 0.35],
    breatheColor: 'rgba(255, 100, 140, 0.3)',
    tunnelShape: 0,
  },
  audio: {
    binauralRange: [7, 3],
    carrierFreq: 110,
    droneFreq: 55,
    droneFifth: 82,
    lfoSpeed: 0.05,
    filterCutoff: 450,
    warmth: 0.9,
  },
  stages: [
    {
      name: 'settling',
      duration: 40,
      intensity: 0.2,
      texts: [],
      textInterval: 99,
      breathCycle: 7,
      breathPattern: { inhale: 3.5, exhale: 3.5 },
      spiralSpeed: 0.8,
      interactions: [
        { type: 'breath-sync', triggerAt: 5, duration: 25 },
      ],
    },
    {
      name: 'invitation',
      duration: stageDurations['invitation'] ?? 55,
      intensity: 0.3,
      texts: generatedTexts['invitation'] ?? [],
      textInterval: 10,
      breathCycle: 8,
      breathPattern: { inhale: 4, holdIn: 1, exhale: 3 },
      spiralSpeed: 0.85,
      interactions: [
        { type: 'voice-gate', triggerAt: 52, duration: 20, data: { text: 'do you want to go deeper?' } },
      ],
    },
    {
      name: 'surrender',
      duration: stageDurations['surrender'] ?? 70,
      intensity: 0.55,
      texts: generatedTexts['surrender'] ?? [],
      textInterval: 9,
      breathCycle: 9,
      breathPattern: { inhale: 4, holdIn: 2, exhale: 3 },
      spiralSpeed: 0.7,
      fractionationDip: 0.25,
      interactions: [
        { type: 'voice-gate', triggerAt: 67, duration: 20, data: { text: 'do you want to surrender completely?' } },
      ],
    },
    {
      name: 'devotion',
      duration: stageDurations['devotion'] ?? 75,
      intensity: 0.8,
      texts: generatedTexts['devotion'] ?? [],
      textInterval: 9,
      breathCycle: 10,
      breathPattern: { inhale: 4, holdIn: 3, exhale: 3 },
      spiralSpeed: 0.55,
      fractionationDip: 0.4,
    },
    {
      name: 'ecstasy',
      duration: stageDurations['ecstasy'] ?? 75,
      intensity: 1.0,
      texts: generatedTexts['ecstasy'] ?? [],
      textInterval: 9,
      breathCycle: 12,
      breathPattern: { inhale: 4, holdIn: 4, exhale: 4 },
      spiralSpeed: 0.25,
    },
    {
      name: 'afterglow',
      duration: stageDurations['afterglow'] ?? 40,
      intensity: 0.35,
      texts: generatedTexts['afterglow'] ?? [],
      textInterval: 7,
      breathCycle: 8,
      breathPattern: { inhale: 4, exhale: 4 },
      spiralSpeed: 0.8,
    },
  ],
  photoWarning: true,
  contentWarning: 'This session contains erotic\nhypnotic content.\n18+ only.',
};
