import type { SessionConfig } from '../session';

export const erotic: SessionConfig = {
  id: 'erotic',
  name: 'Surrender',
  description: 'An erotic submission hypnosis session blending dominance framing with permissive Ericksonian technique.',
  icon: '\u{1F525}',
  theme: {
    textColor: '#ff80a0',
    textGlow: 'rgba(255, 80, 120, 0.55)',
    primaryColor: [0.7, 0.1, 0.25],
    secondaryColor: [0.55, 0.05, 0.35],
    accentColor: [0.9, 0.2, 0.5],
    bgColor: [0.06, 0.01, 0.03],
    particleColor: [0.8, 0.15, 0.4],
    breatheColor: 'rgba(255, 80, 130, 0.35)',
    tunnelShape: 1.0,
  },
  audio: {
    binauralRange: [7, 4],
    carrierFreq: 110,
    droneFreq: 55,
    droneFifth: 82,
    lfoSpeed: 0.06,
    filterCutoff: 500,
    warmth: 0.85,
  },
  stages: [
    {
      name: 'invitation',
      duration: 30,
      intensity: 0.3,
      texts: [
        'you chose to be here',
        'something about this\ndraws you in',
        'notice the warmth\nbeginning',
        'you already know\nwhat you want',
        'it is safe\nto want this',
        'let yourself\nbe curious',
      ],
      textInterval: 6,
      breathCycle: 7,
      spiralSpeed: 1.0,
      interactions: [
        {
          type: 'voice-gate',
          triggerAt: 25,
          duration: 5,
          data: { text: 'do you want to go deeper?' },
        },
      ],
    },
    {
      name: 'surrender',
      duration: 40,
      intensity: 0.55,
      texts: [
        'your body knows\nwhat to do',
        'feel the warmth\nspreading',
        'it feels good\nto let go',
        'every breath makes you\nmore receptive',
        'you don\'t need\nto resist',
        'the pleasure builds\nwhen you stop trying',
        'that\'s it\njust like that',
      ],
      textInterval: 7,
      breathCycle: 8,
      spiralSpeed: 0.85,
      fractionationDip: 0.2,
      interactions: [
        {
          type: 'voice-gate',
          triggerAt: 35,
          duration: 5,
          data: { text: 'do you want to surrender?' },
        },
      ],
    },
    {
      // Pure narration — no interruptions during deep trance
      name: 'devotion',
      duration: 55,
      intensity: 0.8,
      texts: [
        'you want to go deeper',
        'pleasure grows\nwith every breath',
        'you love\nhow this feels',
        'so easy to obey',
        'trust this feeling',
        'your mind is soft\nand open',
        'you were made\nfor this',
        'deeper still',
      ],
      textInterval: 8,
      breathCycle: 9,
      spiralSpeed: 0.6,
      fractionationDip: 0.4,
    },
    {
      name: 'ecstasy',
      duration: 65,
      intensity: 1.0,
      texts: [
        'you belong\nto this moment',
        'pure surrender',
        'waves of pleasure',
        'deeper\nand deeper',
        'good',
        'let it consume you',
        'bliss',
        'you are perfect\nlike this',
        'give in completely',
        'there is nothing\nbut this feeling',
      ],
      textInterval: 8,
      breathCycle: 10,
      spiralSpeed: 0.4,
      fractionationDip: 0.6,
    },
    {
      name: 'afterglow',
      duration: 35,
      intensity: 0.4,
      texts: [
        'slowly returning',
        'carrying this warmth\nwith you',
        'you did so well',
        'remember this feeling',
        'gentle now',
        'you can come back\nwhenever you want',
      ],
      textInterval: 7,
      breathCycle: 11,
      spiralSpeed: 0.9,
    },
  ],
  photoWarning: true,
  contentWarning: 'This session contains erotic hypnotic content. 18+ only.',
};
