import type { SessionConfig } from '../session';

export const focus: SessionConfig = {
  id: 'focus',
  name: 'Focus',
  description: 'An alpha-state session for clarity, concentration, and effortless flow.',
  icon: '\u{26A1}',
  theme: {
    textColor: '#70e8e8',
    textGlow: 'rgba(80, 220, 230, 0.55)',
    primaryColor: [0.05, 0.65, 0.7],
    secondaryColor: [0.1, 0.45, 0.6],
    accentColor: [0.15, 0.85, 0.9],
    bgColor: [0.01, 0.04, 0.06],
    particleColor: [0.1, 0.7, 0.75],
    breatheColor: 'rgba(80, 220, 230, 0.3)',
  },
  audio: {
    binauralRange: [12, 8],
    carrierFreq: 150,
    droneFreq: 75,
    droneFifth: 112,
    lfoSpeed: 0.12,
    filterCutoff: 900,
    warmth: 0.4,
  },
  stages: [
    {
      name: 'centering',
      duration: 25,
      intensity: 0.3,
      texts: [
        'find your center',
        'let distractions\nfall away',
        'one point of focus',
        'everything else\ncan wait',
        'just this\nright now',
      ],
      textInterval: 6,
      breathCycle: 7,
      spiralSpeed: 1.1,
    },
    {
      name: 'sharpening',
      duration: 35,
      intensity: 0.6,
      texts: [
        'your mind\nis becoming clear',
        'focused energy\nflows through you',
        'distractions dissolve\non contact',
        'sharp and present',
        'every thought\nhas purpose',
        'the noise fades',
      ],
      textInterval: 7,
      breathCycle: 8,
      spiralSpeed: 0.9,
    },
    {
      name: 'flow',
      duration: 90,
      intensity: 0.8,
      texts: [
        'clarity',
        'flow',
        'effortless focus',
        'sharp',
        'present',
        'unstoppable',
        'locked in',
      ],
      textInterval: 14,
      breathCycle: 9,
      spiralSpeed: 0.7,
    },
    {
      name: 'release',
      duration: 20,
      intensity: 0.3,
      texts: [
        'carrying this focus\nwith you',
        'sharp and clear',
        'ready for anything',
        'go',
      ],
      textInterval: 6,
      breathCycle: 7,
      spiralSpeed: 1.0,
    },
  ],
  photoWarning: true,
  contentWarning: null,
};
