import type { SessionConfig } from '../session';
import { generatedTexts, stageDurations, stageInteractions } from './relax-texts';

export const relax: SessionConfig = {
  id: 'relax',
  name: 'Relax',
  description: 'A gentle descent into deep relaxation using Ericksonian pacing and leading.',
  icon: '\u{1F9D8}',
  theme: {
    textColor: '#c8b8ff',
    textGlow: 'rgba(160, 120, 255, 0.6)',
    primaryColor: [0.45, 0.25, 0.85],
    secondaryColor: [0.25, 0.3, 0.75],
    accentColor: [0.6, 0.4, 1.0],
    bgColor: [0.03, 0.02, 0.08],
    particleColor: [0.5, 0.35, 0.9],
    breatheColor: 'rgba(160, 120, 255, 0.35)',
  },
  audio: {
    binauralRange: [10, 4],
    carrierFreq: 120,
    droneFreq: 60,
    droneFifth: 90,
    lfoSpeed: 0.08,
    filterCutoff: 600,
    warmth: 0.7,
  },
  stages: [
    {
      name: 'settle',
      duration: stageDurations['settle'] ?? 45,
      intensity: 0.2,
      texts: generatedTexts['settle'] ?? [],
      textInterval: 10,
      breathCycle: 14,
      breathPattern: { inhale: 5, holdIn: 3, exhale: 6 },
      spiralSpeed: 0.8,
      interactions: [
        { type: 'breath-sync', triggerAt: 0, duration: 30 },
      ],
    },
    {
      name: 'induction',
      duration: stageDurations['induction'] ?? 50,
      intensity: 0.3,
      texts: generatedTexts['induction'] ?? [],
      textInterval: 9,
      breathCycle: 9,
      breathPattern: { inhale: 4, holdIn: 1, exhale: 4 },
      spiralSpeed: 0.85,
    },
    {
      name: 'deepening',
      duration: stageDurations['deepening'] ?? 60,
      intensity: 0.55,
      texts: generatedTexts['deepening'] ?? [],
      textInterval: 9,
      breathCycle: 10,
      breathPattern: { inhale: 4, holdIn: 2, exhale: 6 },
      spiralSpeed: 0.7,
      fractionationDip: 0.3,
      interactions: [
        { type: 'gate', triggerAt: 50, duration: 20, data: { text: 'would you like to go deeper?' } },
      ],
    },
    {
      name: 'trance',
      duration: stageDurations['trance'] ?? 70,
      intensity: 0.8,
      texts: generatedTexts['trance'] ?? [],
      textInterval: 9,
      breathCycle: 11,
      breathPattern: { inhale: 4, holdIn: 3, exhale: 8 },
      spiralSpeed: 0.55,
      fractionationDip: 0.4,
    },
    {
      name: 'deep',
      duration: stageDurations['deep'] ?? 60,
      intensity: 0.95,
      texts: generatedTexts['deep'] ?? [],
      textInterval: 12,
      breathCycle: 12,
      breathPattern: { inhale: 4, holdIn: 4, exhale: 8, holdOut: 4 },
      spiralSpeed: 0.3,
      fractionationDip: 0.55,
    },
    {
      name: 'emergence',
      duration: stageDurations['emergence'] ?? 40,
      intensity: 0.3,
      texts: generatedTexts['emergence'] ?? [],
      textInterval: 8,
      breathCycle: 10,
      breathPattern: { inhale: 5, exhale: 5 },
      spiralSpeed: 0.9,
    },
  ],
  photoWarning: true,
  contentWarning: null,
};
