import type { SessionConfig } from '../session';
import { generatedTexts, stageDurations, stageInterludes } from './relax-v3-texts';

export const relaxV3: SessionConfig = {
  id: 'relax-v3',
  name: 'Deep Relax',
  description: 'An immersive descent into deep relaxation — utilization, embedded commands, and sensory deepening.',
  icon: '\u{1F30A}',
  theme: {
    textColor: '#c8b8ff',
    textGlow: 'rgba(160, 120, 255, 0.6)',
    primaryColor: [0.45, 0.25, 0.85],
    secondaryColor: [0.25, 0.3, 0.75],
    accentColor: [0.6, 0.4, 1.0],
    bgColor: [0.03, 0.02, 0.08],
    particleColor: [0.5, 0.35, 0.9],
    breatheColor: 'rgba(160, 120, 255, 0.35)',
  },
  audio: {
    binauralRange: [10, 4],
    carrierFreq: 120,
    droneFreq: 60,
    droneFifth: 90,
    lfoSpeed: 0.08,
    filterCutoff: 600,
    warmth: 0.7,
  },
  stages: [
    {
      name: 'settle',
      duration: stageDurations['settle'] ?? 56,
      intensity: 0.15,
      texts: generatedTexts['settle'] ?? [],
      textInterval: 10,
      breathCycle: 14,
      breathPattern: { inhale: 5, holdIn: 3, exhale: 6 },
      spiralSpeed: 0.8,
      interlude: stageInterludes['settle'],
      interactions: [
        { type: 'breath-sync', triggerAt: 0, duration: 30, data: { clipId: 'relax_breathe' } },
      ],
      ambient: { melodyLevel: 0.4, noiseLevel: 0.15, filterMax: 1400, padLevel: 0.35 },
    },
    {
      name: 'induction',
      duration: stageDurations['induction'] ?? 90,
      intensity: 0.3,
      texts: generatedTexts['induction'] ?? [],
      textInterval: 9,
      breathCycle: 10,
      breathPattern: { inhale: 4, holdIn: 1, exhale: 5 },
      spiralSpeed: 0.8,
      interlude: stageInterludes['induction'],
      ambient: { melodyLevel: 0.3, noiseLevel: 0.2, filterMax: 1200, padLevel: 0.4 },
    },
    {
      name: 'deepening',
      duration: stageDurations['deepening'] ?? 120,
      intensity: 0.55,
      texts: generatedTexts['deepening'] ?? [],
      textInterval: 9,
      breathCycle: 11,
      breathPattern: { inhale: 4, holdIn: 2, exhale: 6 },
      spiralSpeed: 0.65,
      fractionationDip: 0.3,
      interlude: stageInterludes['deepening'],
      interactions: [
        { type: 'gate', triggerAt: stageDurations['deepening'] ?? 115, duration: 10, data: { text: 'would you like to go deeper?', clipId: 'relax_deeper' } },
      ],
      ambient: { melodyLevel: 0.15, noiseLevel: 0.3, filterMax: 900, padLevel: 0.45 },
    },
    {
      name: 'post_gate',
      duration: stageDurations['post_gate'] ?? 16,
      intensity: 0.6,
      texts: generatedTexts['post_gate'] ?? [],
      textInterval: 12,
      breathCycle: 11,
      breathPattern: { inhale: 4, holdIn: 2, exhale: 6 },
      spiralSpeed: 0.6,
      ambient: { melodyLevel: 0.1, noiseLevel: 0.35, filterMax: 800, padLevel: 0.5 },
    },
    {
      name: 'trance',
      duration: stageDurations['trance'] ?? 207,
      intensity: 0.8,
      texts: generatedTexts['trance'] ?? [],
      textInterval: 10,
      breathCycle: 12,
      breathPattern: { inhale: 4, holdIn: 3, exhale: 8 },
      spiralSpeed: 0.5,
      fractionationDip: 0.4,
      interlude: stageInterludes['trance'],
      ambient: { melodyLevel: 0, noiseLevel: 0.4, filterMax: 600, padLevel: 0.55, warmth: 0.85 },
    },
    {
      name: 'deep',
      duration: stageDurations['deep'] ?? 44,
      intensity: 0.95,
      texts: generatedTexts['deep'] ?? [],
      textInterval: 12,
      breathCycle: 13,
      breathPattern: { inhale: 4, holdIn: 4, exhale: 8, holdOut: 4 },
      spiralSpeed: 0.3,
      interlude: stageInterludes['deep'],
      ambient: { melodyLevel: 0, noiseLevel: 0.5, filterMax: 400, padLevel: 0.6, warmth: 0.95 },
    },
    {
      name: 'emergence',
      duration: stageDurations['emergence'] ?? 75,
      intensity: 0.3,
      texts: generatedTexts['emergence'] ?? [],
      textInterval: 8,
      breathCycle: 10,
      breathPattern: { inhale: 5, exhale: 5 },
      spiralSpeed: 0.85,
      interlude: stageInterludes['emergence'],
      ambient: { melodyLevel: 0.35, noiseLevel: 0.15, filterMax: 1400, padLevel: 0.35, warmth: 0.6 },
    },
  ],
  photoWarning: true,
  contentWarning: null,
};
