import type { SessionConfig } from '../session';

export const sleep: SessionConfig = {
  id: 'sleep',
  name: 'Sleep',
  description: 'A slow, gentle descent into deep sleep. No emergence — fades to black.',
  icon: '\u{1F319}',
  theme: {
    textColor: '#8090cc',
    textGlow: 'rgba(80, 100, 180, 0.5)',
    primaryColor: [0.15, 0.18, 0.5],
    secondaryColor: [0.1, 0.1, 0.35],
    accentColor: [0.25, 0.2, 0.65],
    bgColor: [0.01, 0.01, 0.04],
    particleColor: [0.2, 0.2, 0.55],
    breatheColor: 'rgba(80, 100, 180, 0.25)',
  },
  audio: {
    binauralRange: [3, 1],
    carrierFreq: 100,
    droneFreq: 50,
    droneFifth: 75,
    lfoSpeed: 0.04,
    filterCutoff: 400,
    warmth: 0.85,
  },
  stages: [
    {
      name: 'settle',
      duration: 40,
      intensity: 0.2,
      texts: [
        'your eyes are open\nfor now',
        'notice how heavy\nthey feel',
        'your bed is waiting',
        'there is nothing left\nto do today',
        'let the screen\nhold your gaze',
        'you are already\nslowing down',
      ],
      textInterval: 8,
      breathCycle: 8,
      spiralSpeed: 0.8,
    },
    {
      name: 'drift',
      duration: 50,
      intensity: 0.45,
      texts: [
        'letting your eyelids\ngrow heavier',
        'the screen becomes\na window into sleep',
        'thoughts dissolving\nlike clouds',
        'your body knows\nhow to do this',
        'drifting now',
        'each blink\nlasts a little longer',
      ],
      textInterval: 10,
      breathCycle: 10,
      spiralSpeed: 0.6,
    },
    {
      name: 'descent',
      duration: 60,
      intensity: 0.7,
      texts: [
        'sinking into softness',
        'everything is quiet',
        'the world outside\nhas gone to sleep',
        'you are following',
        'down\nand down',
        'warm and heavy',
      ],
      textInterval: 12,
      breathCycle: 12,
      spiralSpeed: 0.4,
    },
    {
      name: 'deep sleep',
      duration: 90,
      intensity: 0.9,
      texts: [
        'sleep',
        'rest',
        'safe',
        'deep',
        'still',
      ],
      textInterval: 20,
      breathCycle: 14,
      spiralSpeed: 0.2,
    },
  ],
  photoWarning: true,
  contentWarning: null,
};
